version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: deliveryapp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
